# Generated by Django 4.0.3 on 2023-02-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPTSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptInteract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('gpt_answer', models.JSONField()),
                ('wiki_result', models.JSONField()),
                ('google_result', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='WikiSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.JSONField()),
                ('text', models.TextField()),
            ],
        ),
    ]
